### ISSUE TITLE
Export `RcpClient` class

### ISSUE THREAD

**Issue by ostafen** [sublabdev/substrate-client-kotlin#6]
Hey, guys, currently `RpcClient` class is marked as `internal` [here](https://github.com/sublabdev/substrate-client-kotlin/blob/main/src/main/kotlin/dev/sublab/substrate/rpcClient/RpcClient.kt#L54) and cannot be instantiated to make calls to custom `rpc` endpoints.
Is there any issue with making this class exposed? I can submit a MR for that

**Comment by posplaw** [comment]
This was resolved with #4
